// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ukY6MRV7oJCHhUJIiBW7tB4jOLNn9Nk',
    appId: '1:392187124440:web:239fb8ef7f9b2913fa95ad',
    messagingSenderId: '392187124440',
    projectId: 'daretoyoufirebase',
    authDomain: 'daretoyoufirebase.firebaseapp.com',
    storageBucket: 'daretoyoufirebase.appspot.com',
    measurementId: 'G-4D9X8EY36K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7vuAI9Tr1HZqTMLzC0dvOcua_23P9cPA',
    appId: '1:392187124440:android:3a5115c3c6f992e7fa95ad',
    messagingSenderId: '392187124440',
    projectId: 'daretoyoufirebase',
    storageBucket: 'daretoyoufirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjuk8gwnti1Be0CAaesHEiCbp7w3Wpns',
    appId: '1:392187124440:ios:fc1cd52b043253bbfa95ad',
    messagingSenderId: '392187124440',
    projectId: 'daretoyoufirebase',
    storageBucket: 'daretoyoufirebase.appspot.com',
    iosClientId: '392187124440-6atjv27l5t23p3d44iontoii1vl5li7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.daretoyouapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFjuk8gwnti1Be0CAaesHEiCbp7w3Wpns',
    appId: '1:392187124440:ios:fc1cd52b043253bbfa95ad',
    messagingSenderId: '392187124440',
    projectId: 'daretoyoufirebase',
    storageBucket: 'daretoyoufirebase.appspot.com',
    iosClientId: '392187124440-6atjv27l5t23p3d44iontoii1vl5li7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.daretoyouapp',
  );
}
